### ISSUE TITLE
Switch to official Tarantool Docker images (Alpine Linux)

### ISSUE THREAD

**Issue by rtsisyk** [tarantool/try#12]
Please switch Dockerfile to official tarantool/tarantool:1.7 Docker images based on Alpine Linux. 
We should eat our own dog food.

It is also worth mentioning that `tarantool-try` images are regenerated automatically by cron.
As result try.tarantool.org always has the latest version of Tarantool.

**Comment by racktear** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;0yamMLc1&#x2F;13-switch-try-tarantool-org-to-official-alpine-image"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> Switch try.tarantool.org to official Alpine image</a>

**Comment by racktear** [comment]
Done.
