### ISSUE TITLE
Scroll is broken

### ISSUE THREAD

**Issue by nekufa** [tarantool/try#16]
With latest site updates scroll for "try frame" was broken.  
No scrollbar, mousewheel is useless

![image](https://user-images.githubusercontent.com/405067/33488074-87cc68c2-d6c0-11e7-98db-a04354bbe0c4.png)

**Comment by bigbes** [comment]
probably duplicate of https://github.com/tarantool/try/issues/15

**Comment by nekufa** [comment]
I'm sorry, duplicate for #15
