### ISSUE TITLE
[8pt] Support English language for the tutorial tab

### ISSUE THREAD

**Issue by artur-barsegyan** [tarantool/try#35]
### Motivation

We want to let the English-speaking part of the community to have used the Try Tarantool service. The current version of the frontend module can't fetch different files for different types of language.

We've already translated the tutorial and separated tutorial files into two subfolders: 'ru' and 'en'. See "/front/tutorial/en/" path. 

### What needs to do

- Support to show tutorial with user's browser language. As I understand we can fetch this data via JavaScript and change the language in realtime. If the user's language is missing by default show the tutorial in Russian.
- Add language selector for users who want to select the more appropriate language.

**Comment by rgbabaev** [comment]
Design task: https://github.com/tarantool/ux_ui/issues/93

**Comment by rgbabaev** [comment]
Resolved in https://gitlab.com/tarantool/tarantool.io/try-cartridge/-/merge_requests/15
