### ISSUE TITLE
Add sandboxing

### ISSUE THREAD

**Issue by kostja** [tarantool/try#4]
To make some people less mad, sandbox the container:
Add this:

os.execute = nil
os.exit = nil
os.rename = nil
os.tmpname = nil
os.remove = nil
io = nil
require = nil
package = nil

to:
https://github.com/tarantool/try/blob/master/try/container/container.lua

check that tutorial still works.

**Comment by rtsisyk** [comment]
I also banned `fio` and `socket`.
