### ISSUE TITLE
Support '&' (ampersand)

### ISSUE THREAD

**Issue by kostja** [tarantool/try#5]
Moved from https://github.com/tarantool/tarantool/issues/619
```
tarantool> a = "&"
---
- error: '[string "a = ""]:1: unfinished string near ''<eof>'''
```
from the command line: 
```
tarantool> a = "&"
---
...

tarantool> a
---
- '&'
...
```

**Comment by Sulverus** [comment]
Done. Awaiting for check. Commands encoding updated with encodeURIComponent().
